#! /bin/bash
rm -rf /tmp/compile-ptx-src-a*.ptx
rm -rf /tmp/compile-ptx-src-a*.cubin
rm -rf /tmp/compile-ptx-src-b*.ptx
rm -rf /tmp/compile-ptx-src-b*.cubin
rm -rf /tmp/compile-ptx-src-c*.ptx
rm -rf /tmp/compile-ptx-src-c*.cubin
rm -rf /tmp/compile-ptx-src-d*.ptx
rm -rf /tmp/compile-ptx-src-d*.cubin
rm -rf /tmp/compile-ptx-src-e*.ptx
rm -rf /tmp/compile-ptx-src-e*.cubin
rm -rf /tmp/compile-ptx-src-f*.ptx
rm -rf /tmp/compile-ptx-src-f*.cubin
rm -rf /tmp/compile-ptx-src-g*.ptx
rm -rf /tmp/compile-ptx-src-g*.cubin
rm -rf /tmp/compile-ptx-src-h*.ptx
rm -rf /tmp/compile-ptx-src-h*.cubin
rm -rf /tmp/compile-ptx-src-i*.ptx
rm -rf /tmp/compile-ptx-src-i*.cubin
rm -rf /tmp/compile-ptx-src-j*.ptx
rm -rf /tmp/compile-ptx-src-j*.cubin
rm -rf /tmp/compile-ptx-src-k*.ptx
rm -rf /tmp/compile-ptx-src-k*.cubin
rm -rf /tmp/compile-ptx-src-l*.ptx
rm -rf /tmp/compile-ptx-src-l*.cubin
rm -rf /tmp/compile-ptx-src-m*.ptx
rm -rf /tmp/compile-ptx-src-m*.cubin
rm -rf /tmp/compile-ptx-src-n*.ptx
rm -rf /tmp/compile-ptx-src-n*.cubin
rm -rf /tmp/compile-ptx-src-o*.ptx
rm -rf /tmp/compile-ptx-src-o*.cubin
rm -rf /tmp/compile-ptx-src-p*.ptx
rm -rf /tmp/compile-ptx-src-p*.cubin
rm -rf /tmp/compile-ptx-src-q*.ptx
rm -rf /tmp/compile-ptx-src-q*.cubin
rm -rf /tmp/compile-ptx-src-r*.ptx
rm -rf /tmp/compile-ptx-src-r*.cubin
rm -rf /tmp/compile-ptx-src-s*.ptx
rm -rf /tmp/compile-ptx-src-s*.cubin
rm -rf /tmp/compile-ptx-src-t*.ptx
rm -rf /tmp/compile-ptx-src-t*.cubin
rm -rf /tmp/compile-ptx-src-u*.ptx
rm -rf /tmp/compile-ptx-src-u*.cubin
rm -rf /tmp/compile-ptx-src-v*.ptx
rm -rf /tmp/compile-ptx-src-v*.cubin
rm -rf /tmp/compile-ptx-src-w*.ptx
rm -rf /tmp/compile-ptx-src-w*.cubin
rm -rf /tmp/compile-ptx-src-x*.ptx
rm -rf /tmp/compile-ptx-src-x*.cubin
rm -rf /tmp/compile-ptx-src-y*.ptx
rm -rf /tmp/compile-ptx-src-y*.cubin
rm -rf /tmp/compile-ptx-src-z*.ptx
rm -rf /tmp/compile-ptx-src-z*.cubin
rm -rf /tmp/compile-ptx-src-0*.ptx
rm -rf /tmp/compile-ptx-src-0*.cubin
rm -rf /tmp/compile-ptx-src-1*.ptx
rm -rf /tmp/compile-ptx-src-1*.cubin
rm -rf /tmp/compile-ptx-src-2*.ptx
rm -rf /tmp/compile-ptx-src-2*.cubin
rm -rf /tmp/compile-ptx-src-3*.ptx
rm -rf /tmp/compile-ptx-src-3*.cubin
rm -rf /tmp/compile-ptx-src-4*.ptx
rm -rf /tmp/compile-ptx-src-4*.cubin
rm -rf /tmp/compile-ptx-src-5*.ptx
rm -rf /tmp/compile-ptx-src-5*.cubin
rm -rf /tmp/compile-ptx-src-6*.ptx
rm -rf /tmp/compile-ptx-src-6*.cubin
rm -rf /tmp/compile-ptx-src-7*.ptx
rm -rf /tmp/compile-ptx-src-7*.cubin
rm -rf /tmp/compile-ptx-src-8*.ptx
rm -rf /tmp/compile-ptx-src-8*.cubin
rm -rf /tmp/compile-ptx-src-9*.ptx
rm -rf /tmp/compile-ptx-src-9*.cubin
